### ISSUE TITLE
Running main.py with a single input_params gives the same accuracy 

### ISSUE THREAD

**Issue by RoySadaka** [stkeky/valar-morghulis#1]
Hey, 
I noticed your work on GOT's death prediction, pretty awesome stuff!
I wonder if I'm doing something wrong when i run it with all input_params, and 
`exclude_rows = range(1000,1500)` (just to make it a bit challenge)
i get accuracy:  0.762102351314
but then when i disable all input_params and leave just one, say 
`input_params = ['book5']`
i get accuracy:  0.738589211659, when i was expecting a big drop in accuracy, i also tried different **single** 
input_params and got the same high accuracy.
Do you know why accuracy is so high with a single param?

Thank you in advance
Roy.

**Comment by Cobrijani** [comment]
Hey Roy,
Thanks for checking out our project!
Running neural network with only 'book5' as an attribute should not be surprising to give almost 74% accuracy since that attribute represents if character appeared in fifth book and because of that there is high chance that if character appears in fifth book that he is alive. That also applies if character does not appears in fifth book there is high chance that he is already dead.
Could you provide me test results including which attributes were used in training and what was the accuracy?

Best regards,
Stefan.

**Comment by Cobrijani** [comment]
Closed for inactivity.
